# è®¢é˜…é”šç‚¹ï¼Œæ’é™¤äº†ä¸€äº›èŠ‚ç‚¹ï¼Œä¾‹å¦‚ åŒ…å«å‰©ä½™ï¼Œå®˜ç½‘ï¼Œåˆ°æœŸï¼Œä¹Ÿå¯ä»¥åœ¨exclude-filteræ·»åŠ ä½ éœ€è¦æ’é™¤çš„èŠ‚ç‚¹
Providers: &Providers { exclude-filter: "Expire|åˆ°æœŸ|å‰©ä½™|Traffic|ç½‘å€|å®˜ç½‘|è¿‡æœŸ", type: http, interval: 86400, health-check: { enable: true, url: https://www.gstatic.com/generate_204, interval: 300 } }
# å®˜æ–¹é…ç½®æ–‡æ¡£: https://wiki.metacubex.one/config/proxy-providers/
proxy-providers:
  p1:
    <<: *Providers
    url: https://al121.cc/#/register?code=R7vdKxbE
    path: ./proxy_provider/p1.yaml
    override:
      additional-prefix: 'p1 | '  # è®¢é˜…èŠ‚ç‚¹å‰ç¼€ï¼Œæ–¹ä¾¿åŒºåˆ†è¯¥èŠ‚ç‚¹å±äºå“ªä¸ªè®¢é˜…é“¾æ¥ ä¾‹å¦‚`p1 | é¦™æ¸¯ğŸ‡­ğŸ‡°

  p2:
    <<: *Providers
    url: https://al121.cc/#/register?code=R7vdKxbE
    path: ./proxy_provider/p2.yaml
    override:
      additional-prefix: 'p2 | '

# dnsé…ç½®
dns:
  enable: true
  ipv6: true
  prefer-h3: false
  use-hosts: false
  use-system-hosts: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "+.lan"
    - "+.local"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "localhost.ptlogin2.qq.com"
    - "localhost.sec.qq.com"
    - "localhost.work.weixin.qq.com"
    - "market.xiaomi.com"
    - "*.xiaomi.com"
    - "*.mi.com"
    - "*.miui.com"
    - "*.xiaomi.net"
    - "*.mi.net"
    - "*.miui.net"
    - "*.pcbeta.com"
  default-nameserver:
    - tls://223.5.5.5
    - tls://119.29.29.29
  nameserver:
    - https://1.1.1.1/dns-query
    - https://dns.google.com/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  direct-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

# é€šç”¨é…ç½®
mode: rule
ipv6: true
mixed-port: 7890
allow-lan: true
bind-address: 0.0.0.0
log-level: error
unified-delay: true
find-process-mode: strict
# è§„åˆ™é€‰æ‹©ç¼“å­˜
profile:
    store-selected: true
    store-fake-ip: true
tcp-concurrent: true
keep-alive-interval: 15
keep-alive-idle: 15
disable-keep-alive: true

# GEOé…ç½®
geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
geodata-loader: memconservative
geox-url:
    geoip: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
    geosite: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
    mmdb: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
    asn: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb"

# æ—¶é—´åŒæ­¥
ntp:
    enable: true
    write-to-system: false
    server: ntp1.aliyun.com
    port: 123
    interval: 30

# å…¥ç«™
tun:
    enable: false
    stack: mixed
    auto-route: true
    auto-redirect: false
    auto-detect-interface: true
    dns-hijack:
        - any:53
        - tcp://any:53
    route-exclude-address: []
    mtu: 1500

# å—…æ¢
sniffer:
    enable: false
    force-dns-mapping: true
    parse-pure-ip: true
    override-destination: false
    sniff:
        TLS:
            ports:
                - 443
                - 8443
        HTTP:
            ports:
                - 80
                - 8080-8880
            override-destination: true
        QUIC:
            ports:
                - 443
                - 8443
    force-domain: []
    skip-domain:
        - +.oray.com
        - "Mijia Cloud"
        - "+.push.apple.com"

# é¢æ¿è®¾ç½®
external-controller: 127.0.0.1:9090
secret: ""
external-ui: "./ui"
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# ä»£ç†ç»„é”šç‚¹ï¼Œæ˜¯ä¸ºäº†å‡å°‘é‡å¤é…ç½®
SelectALL: &SelectALL { type: url-test, proxies: [ é¦™æ¸¯, æ¾³é—¨, å°æ¹¾, æ—¥æœ¬, éŸ©å›½, ç¾å›½, è‹±å›½, å¾·å›½, æ³•å›½, å°åº¦, å°å°¼, è¶Šå—, æ³°å›½, æ¾³æ´², å·´è¥¿, è·å…°, å…¶ä»–, åœŸè€³å…¶, é˜¿æ ¹å»·, æ–°åŠ å¡, è‡ªå»º, DIRECT, REJECT ], hidden: true, include-all: true }
SelectAUTO: &SelectAUTO { type: select, proxies: [ è‡ªåŠ¨é€‰æ‹©, é¦™æ¸¯, æ¾³é—¨, å°æ¹¾, æ—¥æœ¬, éŸ©å›½, ç¾å›½, è‹±å›½, å¾·å›½, æ³•å›½, å°åº¦, å°å°¼, è¶Šå—, æ³°å›½, æ¾³æ´², å·´è¥¿, è·å…°, å…¶ä»–, åœŸè€³å…¶, é˜¿æ ¹å»·, æ–°åŠ å¡, è‡ªå»º, DIRECT, REJECT ], disable-udp: false }
SelectTW: &SelectTW { type: select, proxies: [ å°æ¹¾, æ‰‹åŠ¨é€‰æ‹©, é¦™æ¸¯, æ¾³é—¨, æ—¥æœ¬, éŸ©å›½, ç¾å›½, è‹±å›½, å¾·å›½, æ³•å›½, å°åº¦, å°å°¼, è¶Šå—, æ³°å›½, æ¾³æ´², å·´è¥¿, è·å…°, å…¶ä»–, åœŸè€³å…¶, é˜¿æ ¹å»·, æ–°åŠ å¡, DIRECT, REJECT ], disable-udp: false }
SelectDirect: &SelectDirect { type: select, proxies: [ DIRECT, REJECT, æ‰‹åŠ¨é€‰æ‹©, é¦™æ¸¯, æ¾³é—¨, å°æ¹¾, æ—¥æœ¬, éŸ©å›½, ç¾å›½, è‹±å›½, å¾·å›½, æ³•å›½, å°åº¦, å°å°¼, è¶Šå—, æ³°å›½, æ¾³æ´², å·´è¥¿, è·å…°, å…¶ä»–, åœŸè€³å…¶, é˜¿æ ¹å»·, æ–°åŠ å¡, REJECT ], disable-udp: false }
SelectProxy: &SelectProxy { type: select, proxies: [ æ‰‹åŠ¨é€‰æ‹©, é¦™æ¸¯, æ¾³é—¨, å°æ¹¾, æ—¥æœ¬, éŸ©å›½, ç¾å›½, è‹±å›½, å¾·å›½, æ³•å›½, å°åº¦, å°å°¼, è¶Šå—, æ³°å›½, æ¾³æ´², å·´è¥¿, è·å…°, å…¶ä»–, åœŸè€³å…¶, é˜¿æ ¹å»·, æ–°åŠ å¡, è‡ªå»º, DIRECT, REJECT ], disable-udp: false }
# hidden: true æ˜¯ä¸ºäº†éšè—åœ°åŒºåˆ†ç»„ï¼Œæœ‰éœ€è¦æ˜¾ç¤ºå‡ºæ¥çš„ä½¬å‹å¯ä»¥åˆ é™¤
UrlTest: &UrlTest { type: url-test, interval: 300, tolerance: 50, url: 'https://www.gstatic.com/generate_204', hidden: true, include-all: true, disable-udp: false }
Fallback: &Fallback { type: fallback, interval: 300, tolerance: 50, url: 'https://www.gstatic.com/generate_204', hidden: true, include-all: true, disable-udp: false }

# ä»£ç†ç»„
proxy-groups:
    - { name: æ‰‹åŠ¨é€‰æ‹©, <<: *SelectAUTO, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Rocket.png, include-all: true }
    - { name: è‡ªåŠ¨é€‰æ‹©, <<: *SelectALL, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png }
    - { name: GLOBAL, <<: *SelectDirect, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png, include-all: true }
    - { name: Apple, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple.png }
    - { name: BiliBili, <<: *SelectDirect, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/bilibili_4.png }
    - { name: Claude, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/lobehub/lobe-icons@master/packages/static-png/light/claude-color.png }
    - { name: Disney, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Disney.png }
    - { name: Emby, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Emby.png }
    - { name: Gemini, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/lobehub/lobe-icons@master/packages/static-png/light/gemini-color.png, include-all: true }
    - { name: Linux Do, <<: *SelectProxy, icon: https://github.com/qimiaoliaoss/store/blob/main/images/icon/LinuxDo.png, include-all: true }
    - { name: Github, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png }
    - { name: Google, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png }
    - { name: Microsoft, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png }
    - { name: Netflix, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png }
    - { name: OpenAI, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/lobehub/lobe-icons@master/packages/static-png/light/openai.png }
    - { name: OneDrive, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/OneDrive.png }
    - { name: Steam, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png }
    - { name: Spotify, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png }
    - { name: TikTok, <<: *SelectTW, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok.png }
    - { name: Telegram, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png }
    - { name: Twitter, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png }
    - { name: YouTube, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png}
    - { name: æ¼ç½‘ä¹‹é±¼, <<: *SelectProxy, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png }
    - { name: ç›´è¿, <<: *SelectDirect, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png, hidden: true }
    # è¿™é‡ŒåªåŒ¹é…äº†ä¸€äº›å¸¸ç”¨åœ°åŒºçš„åˆ†ç»„
    - { name: é¦™æ¸¯, <<: *UrlTest, filter: ğŸ‡­ğŸ‡°|é¦™æ¸¯|æ¸¯|HK|HKG|Hong Kong|hong kong|hongkong, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png }
    - { name: æ¾³é—¨, <<: *UrlTest, filter: ğŸ‡²ğŸ‡´|æ¾³é—¨|é—¨|MO|macao, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Macao.png }
    - { name: å°æ¹¾, <<: *UrlTest, filter: ğŸ‡¹ğŸ‡¼|å°æ¹¾|å°|TW|TWN|Taiwan|taiwan|taipei, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png }
    - { name: æ—¥æœ¬, <<: *UrlTest, filter: ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|JP|JPN|Japan|japan|tokyo|osaka, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png }
    - { name: éŸ©å›½, <<: *UrlTest, filter: ğŸ‡°ğŸ‡·|éŸ©å›½|éŸ©|KR|KOR|korea|seoul, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Korea.png }
    - { name: ç¾å›½, <<: *UrlTest, filter: ğŸ‡ºğŸ‡¸|ç¾å›½|ç¾|US|USA|united states|america|los angeles|san jose|silicon valley, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png }
    - { name: è‹±å›½, <<: *UrlTest, filter: ğŸ‡¬ğŸ‡§|è‹±å›½|è‹±|GBR|UK|united kingdom|london, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_Kingdom.png }
    - { name: å¾·å›½, <<: *UrlTest, filter: ğŸ‡©ğŸ‡ª|å¾·å›½|å¾·|DE|DEU|germany|frankfurt, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Germany.png }
    - { name: æ³•å›½, <<: *UrlTest, filter: ğŸ‡«ğŸ‡·|æ³•å›½|æ³•|FR|france|paris, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/France.png }
    - { name: å°åº¦, <<: *UrlTest, filter: ğŸ‡®ğŸ‡³|å°åº¦|IN|IND|india|mumbai, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/France.png }
    - { name: å°å°¼, <<: *UrlTest, filter: ğŸ‡®ğŸ‡©|å°å°¼|å°åº¦å°¼è¥¿äºš|ID|indonesia|jakarta, icon: https://cdn.jsdelivr.net/gh/wanswu/my-backup@main/IconSet/Country/Indonesia.png }
    - { name: è¶Šå—, <<: *UrlTest, filter: ğŸ‡»ğŸ‡³|è¶Šå—|VN|vietnam, icon: https://cdn.jsdelivr.net/gh/wanswu/my-backup@main/IconSet/Country/Vietnam.png }
    - { name: æ³°å›½, <<: *UrlTest, filter: ğŸ‡¹ğŸ‡­|æ³°å›½|TH|thailand|bangkok, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Thailand.png }
    - { name: æ¾³æ´², <<: *UrlTest, filter: ğŸ‡¦ğŸ‡º|æ¾³æ´²|æ¾³å¤§åˆ©äºš|AU|AUS|australia|sydney, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Australia.png }
    - { name: å·´è¥¿, <<: *UrlTest, filter: ğŸ‡§ğŸ‡·|å·´è¥¿|BRA|brazil, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Brazil.png }
    - { name: è·å…°, <<: *UrlTest, filter: ğŸ‡³ğŸ‡±|è·å…°|NL|NLD, icon: https://cdn.jsdelivr.net/gh/wanswu/my-backup@main/IconSet/Country/Netherlands.png }
    - { name: åœŸè€³å…¶, <<: *UrlTest, filter: ğŸ‡¹ğŸ‡·|åœŸè€³å…¶|TUR|Turkey|turkey, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Turkey.png }
    - { name: é˜¿æ ¹å»·, <<: *UrlTest, filter: ğŸ‡¦ğŸ‡·|é˜¿æ ¹å»·|ARG|Argentina|argentina, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Argentina.png }
    - { name: æ–°åŠ å¡, <<: *UrlTest, filter: ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®åŸ|æ–°|SG|SGP|Singapore|singapore, icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png }
    - { name: è‡ªå»º, <<: *UrlTest, filter: 'è‡ªå»º', icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Server.png }
    # é™¤äº†å¸¸ç”¨çš„åœ°åŒºï¼Œå…¶ä»–åœ°åŒºéƒ½æ”¾è¿™é‡Œ
    - { name: å…¶ä»–, <<: *UrlTest, filter: '(?i)^(?!.*(é¦™æ¸¯|å°æ¹¾|æ—¥æœ¬|éŸ©å›½|æ–°åŠ å¡|ç¾å›½|è‹±å›½|å¾·å›½|æ³•å›½|å°åº¦|æ³°å›½|è¶Šå—|å°å°¼|æ¾³å¤§åˆ©äºš|å·´è¥¿|æ¸¯|å°|æ—¥|éŸ©|æ–°|ç¾|è‹±|å¾·|æ³•|å°|æ³°|è¶Š|å°¼|æ¾³|å·´|hk|tw|jp|kr|sg|us|uk|de|fr|in|th|vn|id|au|br)).*', icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png }

# è§„åˆ™é”šç‚¹ï¼Œæ˜¯ä¸ºäº†å‡å°‘é‡å¤é…ç½®
rule-anchor:
    DomainYaml: &DomainYaml { behavior: domain, interval: 86400, proxy: æ‰‹åŠ¨é€‰æ‹©, type: http }
    ClassicalYaml: &ClassicalYaml { behavior: classical, interval: 86400, proxy: æ‰‹åŠ¨é€‰æ‹©, type: http }

# å®˜æ–¹é…ç½®æ–‡æ¡£: https://wiki.metacubex.one/config/rule-providers/
rule-providers:
    # è¿™é‡Œæ˜¯blackmatrix7å¤§ä½¬çš„ä¸€äº›è§„åˆ™å¸¸ç”¨çš„éƒ½åœ¨è¿™é‡Œ æœ‰éœ€è¦çš„ä½¬å‹åœ¨è¿™é‡Œæ·»åŠ å°±å¥½äº†
    Apple: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple_Classical.yaml}
    BiliBili: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BiliBili/BiliBili.yaml }
    China: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/China/China_Classical_No_Resolve.yaml }
    ChinaCustom: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/wanswu/my-backup@main/clash/rule/ChinaCustom.yaml }
    Claude: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Claude/Claude.yaml }
    Disney: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Disney/Disney.yaml }
    Emby: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Emby/Emby.yaml }
    Gemini: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Gemini/Gemini.yaml }
    Github: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub.yaml }
    Google: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.yaml }
    Global: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/wanswu/my-backup@main/clash/rule/Global.yaml }
    Hijacking: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Hijacking/Hijacking.yaml }
    Lan: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Lan/Lan_No_Resolve.yaml }
    Microsoft: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml }
    Mozilla: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Mozilla/Mozilla.yaml }
    Netflix: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix.yaml }
    OpenAI: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml }
    OneDrive: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OneDrive/OneDrive.yaml }
    Steam: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Steam/Steam.yaml }
    Spotify: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Spotify/Spotify.yaml }
    TikTok: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok.yaml }
    Twitter: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Twitter/Twitter.yaml }
    Telegram: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml }
    YouTube: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml }
    DNSLeak: { <<: *ClassicalYaml, url: https://cdn.jsdelivr.net/gh/wanswu/my-backup@main/clash/rule/DNSLeak.yaml }

# å®˜æ–¹é…ç½®æ–‡æ¡£: https://wiki.metacubex.one/config/rules/
rules:
    # é¢å¤–æ·»åŠ çš„è§„åˆ™ï¼Œä½¬å‹ä¹Ÿå¯ä»¥è‡ªå·±æ·»åŠ ï¼Œè§„åˆ™ä¼˜å…ˆçº§ä¸ºç”±ä¸Šåˆ°ä¸‹
    # ä»‹ç»ä¸€ä¸‹å¦‚ä½•é…ç½®
    # åŒ¹é…è§„åˆ™,åˆ†ç»„,è§„åˆ™ ä¾‹å¦‚ä¸‹é¢è¿™ä¸ª
    # [åŸŸååŒ¹é…],[linux.do],[ç›´è¿]
    # - DOMAIN-SUFFIX,windows.net,æ‰‹åŠ¨é€‰æ‹©
    # [è¿›ç¨‹åŒ¹é…],[è¿›ç¨‹åç§°],[è§„åˆ™]
    # - PROCESS-NAME,prl_naptd,æ¼ç½‘ä¹‹é±¼
    # [è§„åˆ™åŒ¹é…],[è§„åˆ™é›†],[è§„åˆ™],[ä¸è§£æ]  è¿™é‡Œä¸ä½¿ç”¨GEOIP,privateï¼Œæ˜¯å› ä¸ºæˆ‘æµ‹è¯•ä¸‹æ¥æ„Ÿè§‰ä½¿ç”¨GEOä¼šè®©clashå†…å­˜å˜é«˜æ‰€ä»¥å°±æ²¡ä½¿ç”¨äº†
    - DOMAIN-SUFFIX,linux.do,Linux Do
    - RULE-SET,Lan,ç›´è¿,no-resolve
    - RULE-SET,DNSLeak,æ‰‹åŠ¨é€‰æ‹©
    - RULE-SET,ChinaCustom,ç›´è¿,no-resolve
    - RULE-SET,China,ç›´è¿,no-resolve
    - RULE-SET,Telegram,Telegram
    - RULE-SET,Gemini,Gemini
    - RULE-SET,Google,Google
    - RULE-SET,Global,æ‰‹åŠ¨é€‰æ‹©
    - RULE-SET,Github,Github
    - RULE-SET,YouTube,YouTube
    - RULE-SET,BiliBili,BiliBili
    - RULE-SET,OneDrive,OneDrive
    - RULE-SET,Microsoft,Microsoft
    - RULE-SET,Mozilla,æ‰‹åŠ¨é€‰æ‹©
    - RULE-SET,TikTok,TikTok
    - RULE-SET,Spotify,Spotify
    - RULE-SET,Netflix,Netflix
    - RULE-SET,Disney,Disney
    - RULE-SET,OpenAI,OpenAI
    - RULE-SET,Twitter,Twitter
    - RULE-SET,Claude,Claude
    - RULE-SET,Steam,Steam
    - RULE-SET,Emby,Emby
    - RULE-SET,Hijacking,DIRECT
    # æ²¡æœ‰åŒ¹é…åˆ°è§„åˆ™çš„å…¨éƒ¨èµ°[æ¼ç½‘ä¹‹é±¼]çš„è¿™ä¸ªè§„åˆ™
    - MATCH,æ¼ç½‘ä¹‹é±¼